In [1]:
import tensorflow as tf

# 1 tf版本

In [2]:
print(tf.__version__)

2.0.0-dev20191002


# 2 张量

张量，有name
变量名是写代码用的，name是用来保存模型用的
模型保存以后就没有变量名了，那么模型通过name区分

# 3 变量

## 3.1 矩阵、特别形式的矩阵、维度（大小）

In [3]:
matrix = tf.Variable([[3, 8, 7, 19], [5, 2, 11, 6], [23, 3, 0, 1]], name='matrix')
zeros_3x4 = tf.Variable(tf.zeros((3, 4)), name='zeros_3x4')
ones_3x2 = tf.Variable(tf.ones((3, 2)), name='ones_3x2')
eye_5 = tf.Variable(tf.eye(5), name='eye_5')

matrix, zeros_3x4, ones_3x2, eye_5, matrix.shape

(<tf.Variable 'matrix:0' shape=(3, 4) dtype=int32, numpy=
 array([[ 3,  8,  7, 19],
        [ 5,  2, 11,  6],
        [23,  3,  0,  1]], dtype=int32)>,
 <tf.Variable 'zeros_3x4:0' shape=(3, 4) dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>,
 <tf.Variable 'ones_3x2:0' shape=(3, 2) dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Variable 'eye_5:0' shape=(5, 5) dtype=float32, numpy=
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], dtype=float32)>,
 TensorShape([3, 4]))

## 3.2 矩阵加、减、点乘、叉乘

In [4]:
m1 = tf.Variable([[2], [1]], name='m3')
m2 = tf.Variable([[1, 2, 3], [2, 3, 4]], name='m2')
m3 = tf.Variable([[1, 2, 3], [-1, 3, -1]], name='m3')
m4 = tf.Variable([[1, 1, 2, -1], [1, 0, -1, 1], [0, -1, 1, 0]], name='m4')

m_add = m2 + m3
m_sub = m2 - m3
m_mul_1 = m1 * m2
m_mul_2 = m2 * m3
m_matmul = tf.matmul(m2, m4)

m1, m2, m3, m4, m_add, m_sub, m_mul_1, m_mul_2, m_matmul

(<tf.Variable 'm3:0' shape=(2, 1) dtype=int32, numpy=
 array([[2],
        [1]], dtype=int32)>,
 <tf.Variable 'm2:0' shape=(2, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int32)>,
 <tf.Variable 'm3:0' shape=(2, 3) dtype=int32, numpy=
 array([[ 1,  2,  3],
        [-1,  3, -1]], dtype=int32)>,
 <tf.Variable 'm4:0' shape=(3, 4) dtype=int32, numpy=
 array([[ 1,  1,  2, -1],
        [ 1,  0, -1,  1],
        [ 0, -1,  1,  0]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 4, 6],
        [1, 6, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 0, 0],
        [3, 0, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 4, 6],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 1,  4,  9],
        [-2,  9, -4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 3, -2,  3,  1],
        [ 5, -2,  5,  1]], dtype=int32)>)

## 3.3 变量的赋值

变量可以用哪个assign赋值，赋值以后，还是原来的对象，内容变化

In [5]:
m2.assign([[1, 1, 1], [2, 2, 2]])
m2

<tf.Variable 'm2:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>

## 3.4 标量

In [6]:
s = tf.Variable(2, name='scalar')
s.numpy()

2

# 4 常量

常量的这种重新赋值，是不同的对象，可以从张量的id不同看出`

In [7]:
c1 = tf.constant(2)
c1

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [8]:
c1 = tf.constant(2, name='const')
c1

<tf.Tensor: shape=(), dtype=int32, numpy=2>