In [8]:
import tensorflow as tf

# 1 创建数据集

tf.data.Dataset.from_tensors

tf.data.Dataset.from_tensor_slices

区别是一个是一个数据， 另一个是打散后多个数据

In [9]:
dataset = tf.data.Dataset.from_tensors([1, 2, 3, 4, 5])
for elem in dataset:
    print(elem.numpy())

[1 2 3 4 5]


In [10]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])
for elem in dataset:
    print(elem.numpy())

1
2
3
4
5


# 2 读取数据集

tf.data.TextLineDataset() 从文本中读取

tf.data.FixedLengthRecordDataset() 从二进制文件中读取

tf.data.TFRecordDataset() 从TF格式记录里面读取

其他方式

# 3 batch操作

batch的入参batch_size表示一个batch的大小，也就是每多少个一个batch。这样不会一下全部加载。加载的batch个数用take控制。

In [11]:
dataset = tf.data.Dataset.range(100)
batched_dataset = dataset.batch(10)
for one_batch in batched_dataset.take(6):
    print(one_batch.numpy())

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49]
[50 51 52 53 54 55 56 57 58 59]


# 4 zip操作

可以看做是data和label的整合。整合的方式是一个data对应一个label。

每个data和label一一对应，比如第一个(data=[0,1,2,3,4], label=0)，再如第二个(data=[1,2,3,4,5], label=1)

In [12]:
m = 16
data = tf.data.Dataset.from_tensor_slices([list(range(i, i+5)) for i in range(m)])
labels = tf.data.Dataset.from_tensor_slices([i for i in range(m)])
dataset = tf.data.Dataset.zip((data, labels))
for elem in dataset:
    print([e.numpy() for e in elem])

[array([0, 1, 2, 3, 4], dtype=int32), 0]
[array([1, 2, 3, 4, 5], dtype=int32), 1]
[array([2, 3, 4, 5, 6], dtype=int32), 2]
[array([3, 4, 5, 6, 7], dtype=int32), 3]
[array([4, 5, 6, 7, 8], dtype=int32), 4]
[array([5, 6, 7, 8, 9], dtype=int32), 5]
[array([ 6,  7,  8,  9, 10], dtype=int32), 6]
[array([ 7,  8,  9, 10, 11], dtype=int32), 7]
[array([ 8,  9, 10, 11, 12], dtype=int32), 8]
[array([ 9, 10, 11, 12, 13], dtype=int32), 9]
[array([10, 11, 12, 13, 14], dtype=int32), 10]
[array([11, 12, 13, 14, 15], dtype=int32), 11]
[array([12, 13, 14, 15, 16], dtype=int32), 12]
[array([13, 14, 15, 16, 17], dtype=int32), 13]
[array([14, 15, 16, 17, 18], dtype=int32), 14]
[array([15, 16, 17, 18, 19], dtype=int32), 15]


# 5 zip的batch操作

In [13]:
m = 16
data = tf.data.Dataset.from_tensor_slices([list(range(i, i+3)) for i in range(m)])
labels = tf.data.Dataset.from_tensor_slices([i for i in range(m)])
dataset = tf.data.Dataset.zip((data, labels))
batched_dataset = dataset.batch(3)
for elem in batched_dataset.take(2):
    print([e.numpy() for e in elem])

[array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]], dtype=int32), array([0, 1, 2], dtype=int32)]
[array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]], dtype=int32), array([3, 4, 5], dtype=int32)]


# 6 shuffle操作

In [14]:
dataset = tf.data.Dataset.range(20)
for elem in dataset:
    print(elem.numpy(), end=' ')
    
print()
shuffled_dataset = dataset.shuffle(6)
for elem in shuffled_dataset:
    print(elem.numpy(), end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 
3 5 2 0 8 6 4 9 11 12 10 14 1 7 17 18 16 13 19 15 

# 7 常用的数据集 

tf.keras.datasets

tf.keras.datasets.xx.load_data()就可以将xx数据集加载

常用的数据集有

boston_housing、cifar10、cifar100、fashion_mnist、imdb、mnist、reuters