In [ ]:
import torch
import numpy as np

np_data = np.arange(6).reshape((2, 3))
torch_data = torch.tensor(np_data) # 张量
tensor2array = torch_data.numpy()

print(
    '\nnumpy array:\n', np_data,
    '\ntorch tensor\n', torch_data,
    '\ntensor to array\n', tensor2array
)

# float 类型
# torch.float16
# torch.float32
# torch.float64

# int 类型
# torch.uint8
# torch.int8
# torch.int16
# torch.int32
# torch.int64


In [57]:
import torch
import numpy as np

np_data = np.array([[1, 2], [1, 2]])
torch_data = torch.tensor(np_data)

np_t = np.array([0, np.pi / 4., np.pi / 2.])
torch_t = torch.tensor(np_t)

# 平均值
np_x = np.arange(5)
torch_x = torch.FloatTensor([i for i in range(5)])
# torch.mean 只能计算float的平均值，不能计算int的平均值，所有必须用FloatTensor

print(
    '\nnumpy.abs:\n', np.abs(np_data),
    '\ntorch.abs:\n', torch.abs(torch_data),
    '\nnumpy.sin:\n', np.sin(np_t),
    '\ntorch.sin:\n', torch.sin(torch_t),
    '\nnumpy.mean\n', np.mean(np_x),
    '\ntorch.mean\n', torch.mean(torch_x)
)


numpy.abs:
 [[1 2]
 [1 2]] 
torch.abs:
 tensor([[1, 2],
        [1, 2]]) 
numpy.sin:
 [0.         0.70710678 1.        ] 
torch.sin:
 tensor([0.0000, 0.7071, 1.0000], dtype=torch.float64) 
numpy.mean
 2.0 
torch.mean
 tensor(2.)


In [59]:
import torch
import numpy as np

# numpy矩阵相乘
na = np.array([[1, 2], [3, 4]])
nb = np.array([[1, 1], [0, 1]])
nc = na @ nb  # nc = np.matmul(na, nb)
nd = na * nb
print(nc, nd, sep='\n')

# torch矩阵相乘
ta = torch.FloatTensor([[1, 2], [3, 4]])
tb = torch.FloatTensor([[1, 1], [0, 1]])
tc = torch.mm(ta, tb)
td = ta * tb
print(tc, td, sep='\n')


[[1 3]
 [3 7]]
[[1 2]
 [0 4]]
tensor([[1., 3.],
        [3., 7.]])
tensor([[1., 2.],
        [0., 4.]])


In [107]:
import torch
from torch.autograd import Variable

# 变量
tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad=True)
print(tensor)
print(variable)
t_mean = torch.mean(tensor * tensor)
v_mean = torch.mean(variable * variable)
print(t_mean)
print(v_mean)

# 反向传播求导数
v_mean.backward()
print(variable.grad)

print(variable)  # Variable形式
print(variable.data)  # tensor形式
print(variable.data.numpy())  # numpy形式，随后输出结果一般用numpy形式


tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]


In [19]:
import os
import torch
import torchvision

# 内置数据集
# workdir = os.getcwd()
# torchvision.datasets.MNIST(
#     root=workdir, 
#     train=True,
#     transform=None, # 对data是否进行修改，比如Normalization
#     target_transform=None, # 对label是否进行修改，比如1,2,...,9变成向量形式
#     download=False # 是否下载
# )

root = os.path.dirname(os.getcwd())
# d = torchvision.datasets.FashionMNIST(root, download=True)
# print(root)


In [31]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader


# 自定义数据集
# 继承 torch.utils.data.Dataset
class MyDataset(Dataset):
    def __len__(self):
        """
        必须实现这个方法，给len()函数用
        :return: 
        """
        pass
    def __getitem__(self, item):
        """
        必须实现这个方法，给datasets[i]下标索引用
        可以for迭代
        :param item: 
        :return: 
        """
        pass
    pass


# 另一种高级的迭代数据集的方式
# torch.utils.data.DataLoader
# num_workers 多线程
# dataloader = DataLoader(dataset, batch_size=4, shuffle=True, num_workers=4)
