In [ ]:
import torch
import numpy as np

np_data = np.arange(6).reshape((2, 3))
torch_data = torch.tensor(np_data) # 张量
tensor2array = torch_data.numpy()

print(
    '\nnumpy array:\n', np_data,
    '\ntorch tensor\n', torch_data,
    '\ntensor to array\n', tensor2array
)

# float 类型
# torch.float16
# torch.float32
# torch.float64

# int 类型
# torch.uint8
# torch.int8
# torch.int16
# torch.int32
# torch.int64


In [57]:
import torch
import numpy as np

np_data = np.array([[1, 2], [1, 2]])
torch_data = torch.tensor(np_data)

np_t = np.array([0, np.pi / 4., np.pi / 2.])
torch_t = torch.tensor(np_t)

# 平均值
np_x = np.arange(5)
torch_x = torch.FloatTensor([i for i in range(5)])
# torch.mean 只能计算float的平均值，不能计算int的平均值，所有必须用FloatTensor

print(
    '\nnumpy.abs:\n', np.abs(np_data),
    '\ntorch.abs:\n', torch.abs(torch_data),
    '\nnumpy.sin:\n', np.sin(np_t),
    '\ntorch.sin:\n', torch.sin(torch_t),
    '\nnumpy.mean\n', np.mean(np_x),
    '\ntorch.mean\n', torch.mean(torch_x)
)


numpy.abs:
 [[1 2]
 [1 2]] 
torch.abs:
 tensor([[1, 2],
        [1, 2]]) 
numpy.sin:
 [0.         0.70710678 1.        ] 
torch.sin:
 tensor([0.0000, 0.7071, 1.0000], dtype=torch.float64) 
numpy.mean
 2.0 
torch.mean
 tensor(2.)


In [59]:
import torch
import numpy as np

# numpy矩阵相乘
na = np.array([[1, 2], [3, 4]])
nb = np.array([[1, 1], [0, 1]])
nc = na @ nb  # nc = np.matmul(na, nb)
nd = na * nb
print(nc, nd, sep='\n')

# torch矩阵相乘
ta = torch.FloatTensor([[1, 2], [3, 4]])
tb = torch.FloatTensor([[1, 1], [0, 1]])
tc = torch.mm(ta, tb)
td = ta * tb
print(tc, td, sep='\n')


[[1 3]
 [3 7]]
[[1 2]
 [0 4]]
tensor([[1., 3.],
        [3., 7.]])
tensor([[1., 2.],
        [0., 4.]])


In [107]:
import torch
from torch.autograd import Variable

# 变量
tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad=True)
print(tensor)
print(variable)
t_mean = torch.mean(tensor * tensor)
v_mean = torch.mean(variable * variable)
print(t_mean)
print(v_mean)

# 反向传播求导数
v_mean.backward()
print(variable.grad)

print(variable)  # Variable形式
print(variable.data)  # tensor形式
print(variable.data.numpy())  # numpy形式，随后输出结果一般用numpy形式


tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]


import torch.nn as nn
import torch.nn.functional as F


# 网络的定义
# torch.nn里面是类，类大写，多单词驼峰
# torch.nn.functional里面是函数，函数小写，多单词下划线

# 线性层（全连接层）
nn.Linear(in_features, out_features, bias)
F.linear(input, weight, bias)

# 卷积层
nn.Conv2d(in_channels=, out_channels=, kernel_size=,
          stride=1, padding=0,
          dilation=1,groups=1, bias=True, padding_mode='zeros')
# dilation膨胀卷积

# groups控制输入和输出之间的连接，可以减小参数
# 28*28*2 3*3*64 --> 26*26*64                parm:2*3*3*64
# 28*28*1 3*3*32 --> 26*26*32|___\26*26*64   parm:1*3*3*32 + 1*3*3*32
# 28*28*1 3*3*32 --> 26*26*32|   /
F.conv2d(input, weight, bias=None, stride=1, padding=0,)

# 转置卷积
nn.ConvTranspose2d()
F.conv_transpose2d()

# 池化Average
nn.AvgPool2d()
F.avg_pool2d()

# 池化层Max
nn.MaxPool2d(return_indices=False, ceil_mode=False)
# return_indices=True 返回池化最大位置坐标
# ceil_mode=False, 5*5--2*2--2*2
# ceil_mode=True, 5*5--2*2--3*3,如果池化除不尽向上取整
# 
F.max_pool2d()
F.max_pool2d_with_indices()

# 反池化Max
nn.MaxUnpool2d()
F.max_unpool2d()

# 分数化Max池化

import os
import torch
import torchvision

# 内置数据集
# workdir = os.getcwd()
# torchvision.datasets.MNIST(
#     root=workdir, 
#     train=True,
#     transform=None, # 对data是否进行修改，比如Normalization
#     target_transform=None, # 对label是否进行修改，比如1,2,...,9变成向量形式
#     download=False # 是否下载
# )

root = os.path.dirname(os.getcwd())
# d = torchvision.datasets.FashionMNIST(root, download=True)
# print(root)


from torch.utils.data import Dataset
from torch.utils.data import DataLoader


# 自定义数据集
# 继承 torch.utils.data.Dataset
class MyDataset(Dataset):
    def __len__(self):
        """
        必须实现这个方法，给len()函数用
        :return: 
        """
        pass
    def __getitem__(self, item):
        """
        必须实现这个方法，给datasets[i]下标索引用
        可以for迭代
        :param item: 
        :return: 
        """
        pass
    pass


# 另一种高级的迭代数据集的方式
# torch.utils.data.DataLoader
# num_workers 多线程
# dataloader = DataLoader(dataset, batch_size=4, shuffle=True, num_workers=4)


In [38]:
import torch
import torch.nn as nn
from torch.autograd import Variable


# 最大池化与反池化
pool = nn.MaxPool2d(
    kernel_size=2,
    stride=2,
    return_indices=True,
    ceil_mode=True
)
unpool = nn.MaxUnpool2d(kernel_size=2, stride=2)
in_data = Variable(
    torch.Tensor([[[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]]]])
    # 为什么必须是1*1*4*4的维度呢
    # 因为是N*C*H*W
)
print('\nin_data\n', in_data)
print(in_data.shape)

out_data, indices = pool(in_data)
print('\nout_data\n', out_data)
print('\nindices\n', indices)

un_data = unpool(out_data, indices)
print('\nun_data\n', un_data)



in_data
 tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])
torch.Size([1, 1, 4, 4])

out_data
 tensor([[[[ 6.,  8.],
          [14., 16.]]]])

indices
 tensor([[[[ 5,  7],
          [13, 15]]]])

un_data
 tensor([[[[ 0.,  0.,  0.,  0.],
          [ 0.,  6.,  0.,  8.],
          [ 0.,  0.,  0.,  0.],
          [ 0., 14.,  0., 16.]]]])


In [51]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable


# 卷积层举例
k = nn.Conv2d(
    in_channels=1,
    out_channels=2,
    kernel_size=3,
    padding=0
)
in_data = Variable(
    torch.Tensor([[[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]]]])
)
print('\nin_data\n', in_data)
print(in_data.shape)

out_data = k(in_data)
print('\nout_data\n', out_data)
print(out_data.shape)


in_data
 tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])
torch.Size([1, 1, 4, 4])

out_data
 tensor([[[[3.2893, 3.7151],
          [4.9928, 5.4186]],

         [[1.8688, 2.4146],
          [4.0519, 4.5977]]]], grad_fn=<MkldnnConvolutionBackward>)
torch.Size([1, 2, 2, 2])


In [74]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

# 激活函数  
# inplace=True就是输出就赋值到输入对象上
# nn.ReLU
# nn.ReLU6
# nn.Sigmoid
# nn.LogSigmoid()
# nn.Threshold()
# nn.Tanh
in_data = Variable(torch.Tensor([range(-10, 10)]))
print('\nin_data\n', in_data)
print(in_data.shape)

out_relu = F.relu(in_data)
print('\nout_relu\n', out_relu)
print(out_relu.shape)

# 为什么是relu6呢？这个6是个经验值，无语
out_relu6 = F.relu6(in_data)
print('\nout_relu6\n', out_relu6)
print(out_relu6.shape)

out_sigmoid = F.sigmoid(in_data)
print('\nout_sigmoid\n', out_sigmoid)
print(out_sigmoid.shape)

softmax = nn.Softmax(dim=1)
out_softmax = softmax(in_data)
print('\nout_softmax\n', out_softmax)
print(out_softmax.shape)



in_data
 tensor([[-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,   1.,
           2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]])
torch.Size([1, 20])

out_relu
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 4., 5., 6., 7.,
         8., 9.]])
torch.Size([1, 20])

out_relu6
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 4., 5., 6., 6.,
         6., 6.]])
torch.Size([1, 20])

out_sigmoid
 tensor([[4.5398e-05, 1.2339e-04, 3.3535e-04, 9.1105e-04, 2.4726e-03, 6.6929e-03,
         1.7986e-02, 4.7426e-02, 1.1920e-01, 2.6894e-01, 5.0000e-01, 7.3106e-01,
         8.8080e-01, 9.5257e-01, 9.8201e-01, 9.9331e-01, 9.9753e-01, 9.9909e-01,
         9.9966e-01, 9.9988e-01]])
torch.Size([1, 20])

out_softmax
 tensor([[3.5416e-09, 9.6272e-09, 2.6169e-08, 7.1136e-08, 1.9337e-07, 5.2563e-07,
         1.4288e-06, 3.8839e-06, 1.0557e-05, 2.8698e-05, 7.8010e-05, 2.1205e-04,
         5.7642e-04, 1.5669e-03, 4.2592e-03, 1.1578e-02, 3.1471e-02, 8.5548e-02

In [72]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable


# BatchNormalization
# momentum 指的是移动平均，之前值的参数
# affine是否使用再学习参数
nn.BatchNorm1d(num_features, eps=1e-5, momentum=0.1, affine=True)

import torch.nn as nn
import torch.nn.functional as F


# 损失函数
nn.L1Loss
F.l1_loss()

nn.SmoothL1Loss
F.smooth_l1_loss()

nn.MSELoss # 平方差函数？
F.mse_loss()

nn.CrossEntropyLoss
F.cross_entropy()

nn.BCELoss
F.binary_cross_entropy()

# 最大似然函数
nn.NLLLoss
F.nll_loss()

nn.NLLLoss2d
F.nll_loss2d()

nn.KLDivLoss
F.kl_div()

nn.HingeEmbeddingLoss
F.hinge_embedding_loss()

nn.CosineEmbeddingLoss
F.cosine_embedding_loss()

In [20]:
import torch
import torch.nn.functional as F
from torch.autograd import Variable

in_data = Variable(torch.Tensor([[[[1, 2],
                                   [3, 4]]]]))
out_pad = F.pad(in_data, pad=[1, 2, 3, 4], value=1.)
# 左pad=1，右pad=2，上pad=3，下pad=4
print(in_data)
print(out_pad)


tensor([[[[1., 2.],
          [3., 4.]]]])
tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 2., 1., 1.],
          [1., 3., 4., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])


import torch


# 优化器
torch.optim.Optimizer(prams, defaluts)

# lr learning rate
torch.optim.Adadelta(params, lr=1.0, rho=0.9, eps=1e-6, weight_decay=0)
torch.optim.Adagrad
torch.optim.Adam
torch.optim.Adamax
torch.optim.ASGD
torch.optim.LBFGS
torch.optim.RMSprop
torch.optim.SGD

In [25]:
import torch.nn as nn


class LinearNet(nn.Module):
    """
    举例全连接模型
    """
    def __init__(self, n_feature, n_hidden, n_output):
        super(LinearNet, self).__init__()
        self.hidden1 = nn.Linear(n_feature, n_hidden)
        self.relu1 = nn.ReLU()
        self.predict = nn.Linear(n_hidden, n_output)
        pass

    def forward(self, x):
        x = self.hidden1(x)
        x = self.relu1(x)
        x = self.predict(x)
        return x


linear_net = LinearNet(1, 10, 1)

# 或者
linear_net2 = nn.Sequential(
    nn.Linear(1, 10),
    nn.ReLU(),
    nn.Linear(10, 1)
)


In [33]:
import torch.nn as nn


class CNN(nn.Module):
    """
    举例卷积
    """
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )
        self.predict = nn.Linear(32 * 7 * 7, 10)
        pass

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = x.view(x.size(0), -1)  # 相当于tensorflow里面的flatten操作
        x = self.predict(x)
        return x
    pass


cnn_model = CNN()
