In [1]:
import numpy as np

In [71]:
# 创建数组，指定数据类型
a = np.array([[i for i in range(r*4, (r+1)*4)] for r in range(5)], dtype=np.float32)
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a, a.dtype)
print(b, b.dtype)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]] float32
[[1 2 3]
 [4 5 6]] int64


In [72]:
# 5x4 reshape一下变 4x5x1
a = a.reshape((4, 5, 1))

print('shape', a.shape) # 数组的维度
print('ndim', a.ndim)   # 数组的轴，也就是rank，也就是shape的的大小
print('size', a.size)   # 数组元素的个数，也就是shape乘起来
print('dtype', a.dtype) # 数组元素数据类型
print('itemsize', a.itemsize) # 数组有元素数据类型的大小，float32， 32/8=4

shape (4, 5, 1)
ndim 3
size 20
dtype float32
itemsize 4


In [83]:
def print_mat(mat, name):
    print(name, '=')
    print(mat)
    print()
    
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [0, 1]])
c = np.array([[2, 4], [3, 1]])

print_mat(a, 'a')
print_mat(b, 'b')
print_mat(c, 'c')

# 矩阵运算
print_mat(b*c, 'b mul c')
print_mat(b@a, 'b matmul a')
# 矩阵转置
print_mat(a.T, 'a\'s transpose')

a =
[[1 2 3]
 [4 5 6]]

b =
[[1 1]
 [0 1]]

c =
[[2 4]
 [3 1]]

b mul c =
[[2 4]
 [0 1]]

b matmul a =
[[5 7 9]
 [4 5 6]]

a's transpose =
[[1 4]
 [2 5]
 [3 6]]



In [87]:
# 索引

c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c[1, 0, ...],\
c[...,2]

(array([100, 101, 102]), array([[  2,  13],
        [102, 113]]))

In [89]:
# 迭代可以for循环逐个rank迭代
# 也可以用flat属性，迭代所有的元素
a = np.array([[1,2,3],
              [4,5,6]
             ])
for i in a.flat:
    print(i)

1
2
3
4
5
6


In [111]:
# 数组的拆分
a = np.array([[1, 2, 3],
              [4, 5, 6]
             ])
# 按照列拆分,水平拆分
c1, c2, c3 = np.hsplit(a, a.shape[1])
print_mat(c1, 'c1')
print_mat(c2, 'c2')
print_mat(c3, 'c3')

# 按照行拆分，竖直拆分
r1, r2 = np.vsplit(a, a.shape[0])
print_mat(r1, 'r1')
print_mat(r2, 'r2')

# 以上都不实用，最好是用array_split可以指定拆分任意维度
r1, r2 = np.array_split(a, a.shape[0])
print_mat(r1, 'r1')
print_mat(r2, 'r2')

c1 =
[[1]
 [4]]

c2 =
[[2]
 [5]]

c3 =
[[3]
 [6]]

r1 =
[[1 2 3]]

r2 =
[[4 5 6]]

r1 =
[[1 2 3]]

r2 =
[[4 5 6]]

